// Wait for site to load
window.addEventListener('load', function () {

    // Draggable elements
    function dragElement(e){var t=0,n=0,o=0,d=0;function l(l){(l=l||window.event).preventDefault(),t=o-l.clientX,n=d-l.clientY,o=l.clientX,d=l.clientY,e.style.top=e.offsetTop-n+"px",e.style.left=e.offsetLeft-t+"px"}function m(){document.onmouseup=null,document.onmousemove=null,document.getElementById("window_IDTITLE").classList.remove("Dragged_State"),document.getElementById("window_tab_IDTITLE").classList.remove("Dragged_State")}document.getElementById("window_tab_IDTITLE").onmousedown=function(e){(e=e||window.event).preventDefault(),o=e.clientX,d=e.clientY,document.onmouseup=m,document.getElementById("window_IDTITLE").classList.add("Dragged_State"),document.getElementById("window_tab_IDTITLE").classList.add("Dragged_State"),document.onmousemove=l}}dragElement(document.getElementById("window_IDTITLE"));
    function dragElement2(e){var t=0,n=0,o=0,d=0;function l(l){(l=l||window.event).preventDefault(),t=o-l.clientX,n=d-l.clientY,o=l.clientX,d=l.clientY,e.style.top=e.offsetTop-n+"px",e.style.left=e.offsetLeft-t+"px"}function m(){document.onmouseup=null,document.onmousemove=null,document.getElementById("window_IDMASON").classList.remove("Dragged_State"),document.getElementById("window_tab_IDMASON").classList.remove("Dragged_State")}document.getElementById("window_tab_IDMASON").onmousedown=function(e){(e=e||window.event).preventDefault(),o=e.clientX,d=e.clientY,document.onmouseup=m,document.getElementById("window_IDMASON").classList.add("Dragged_State"),document.getElementById("window_tab_IDMASON").classList.add("Dragged_State"),document.onmousemove=l}}dragElement2(document.getElementById("window_IDMASON"));
    function dragElement3(e){var t=0,n=0,o=0,d=0;function l(l){(l=l||window.event).preventDefault(),t=o-l.clientX,n=d-l.clientY,o=l.clientX,d=l.clientY,e.style.top=e.offsetTop-n+"px",e.style.left=e.offsetLeft-t+"px"}function m(){document.onmouseup=null,document.onmousemove=null,document.getElementById("window_IDCHIP").classList.remove("Dragged_State"),document.getElementById("window_tab_IDCHIP").classList.remove("Dragged_State")}document.getElementById("window_tab_IDCHIP").onmousedown=function(e){(e=e||window.event).preventDefault(),o=e.clientX,d=e.clientY,document.onmouseup=m,document.getElementById("window_IDCHIP").classList.add("Dragged_State"),document.getElementById("window_tab_IDCHIP").classList.add("Dragged_State"),document.onmousemove=l}}dragElement3(document.getElementById("window_IDCHIP"));
    function dragElement4(e){var t=0,n=0,o=0,d=0;function l(l){(l=l||window.event).preventDefault(),t=o-l.clientX,n=d-l.clientY,o=l.clientX,d=l.clientY,e.style.top=e.offsetTop-n+"px",e.style.left=e.offsetLeft-t+"px"}function m(){document.onmouseup=null,document.onmousemove=null,document.getElementById("window_IDORG").classList.remove("Dragged_State"),document.getElementById("window_tab_IDORG").classList.remove("Dragged_State")}document.getElementById("window_tab_IDORG").onmousedown=function(e){(e=e||window.event).preventDefault(),o=e.clientX,d=e.clientY,document.onmouseup=m,document.getElementById("window_IDORG").classList.add("Dragged_State"),document.getElementById("window_tab_IDORG").classList.add("Dragged_State"),document.onmousemove=l}}dragElement4(document.getElementById("window_IDORG"));
    function dragElement5(e){var t=0,n=0,o=0,d=0;function l(l){(l=l||window.event).preventDefault(),t=o-l.clientX,n=d-l.clientY,o=l.clientX,d=l.clientY,e.style.top=e.offsetTop-n+"px",e.style.left=e.offsetLeft-t+"px"}function m(){document.onmouseup=null,document.onmousemove=null,document.getElementById("window_IDDED").classList.remove("Dragged_State"),document.getElementById("window_tab_IDDED").classList.remove("Dragged_State")}document.getElementById("window_tab_IDDED").onmousedown=function(e){(e=e||window.event).preventDefault(),o=e.clientX,d=e.clientY,document.onmouseup=m,document.getElementById("window_IDDED").classList.add("Dragged_State"),document.getElementById("window_tab_IDDED").classList.add("Dragged_State"),document.onmousemove=l}}dragElement5(document.getElementById("window_IDDED"));
    function dragElement6(e){var t=0,n=0,o=0,d=0;function l(l){(l=l||window.event).preventDefault(),t=o-l.clientX,n=d-l.clientY,o=l.clientX,d=l.clientY,e.style.top=e.offsetTop-n+"px",e.style.left=e.offsetLeft-t+"px"}function m(){document.onmouseup=null,document.onmousemove=null,document.getElementById("window_IDCCP").classList.remove("Dragged_State"),document.getElementById("window_tab_IDCCP").classList.remove("Dragged_State")}document.getElementById("window_tab_IDCCP").onmousedown=function(e){(e=e||window.event).preventDefault(),o=e.clientX,d=e.clientY,document.onmouseup=m,document.getElementById("window_IDCCP").classList.add("Dragged_State"),document.getElementById("window_tab_IDCCP").classList.add("Dragged_State"),document.onmousemove=l}}dragElement6(document.getElementById("window_IDCCP"));
            
})